### ISSUE TITLE
garbage

### ISSUE THREAD

**Issue by ghost** [noahcoolboy/bad-aztupbrew-deobfuscator#1]

**Comment by noahcoolboy** [comment]
![do i give a damn](https://media.tenor.com/lAXDG4aNcbwAAAAS/do-i-give-a-damn.gif)

It says bad in the name, so I don't know what you expected.
This was released to accompany my [blog post](https://v3rmillion.net/showthread.php?tid=1117012) on researching the inner workings of obfuscators.
It should be used as a resource for creating your own deobfuscators, and not as a proper tool.
